# Generated by Django 5.0 on 2024-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_reservation_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(choices=[('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505')], max_length=40, unique=True)),
                ('room_type', models.CharField(choices=[('twn', 'ツイン'), ('dbl', 'ダブル'), ('sng', 'シングル')], max_length=50)),
                ('max_headcount', models.IntegerField(choices=[(1, 1), (2, 2)])),
            ],
        ),
    ]
