# Generated by Django 5.0 on 2024-01-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booked_alter_reservation_room_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='dbl_booked',
            new_name='double_booked',
        ),
        migrations.RenameField(
            model_name='booked',
            old_name='sgl_booked',
            new_name='single_booked',
        ),
        migrations.RenameField(
            model_name='booked',
            old_name='twn_booked',
            new_name='twin_booked',
        ),
    ]
