# Generated by Django 5.0 on 2024-01-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_dbl_booked_booked_double_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
